name: Deploy Lambda Functions

on:
  push:
    branches: [ "main" ]
    paths:
      - "lambdas/*.py"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<GITHUB_DEPLOY_ROLE>
          aws-region: us-east-1

      - name: Detect changed Lambda files
        id: changes
        run: |
          echo "CHANGED=$(git diff --name-only HEAD~1 HEAD | grep '^lambdas/.*\.py$' || true)" >> $GITHUB_ENV

      - name: Deploy changed Lambdas
        if: env.CHANGED != ''
        run: |
          for file in $CHANGED; do
            name=$(basename $file .py)
            zip -j ${name}.zip $file
            echo "Deploying Lambda: ${name}"
            aws lambda update-function-code \
              --function-name ${name} \
              --zip-file fileb://${name}.zip
          done
